# -*- coding: utf-8 -*-
"""Materiały do ćwiczeń płynności: tematy do techniki 4/3/2 i fragmenty do shadowingu.

4/3/2 (Maurice, opisane przez Nationa): to samo opowiadasz trzy razy — najpierw w 4 minuty,
potem w 3, potem w 2. Ten sam materiał, coraz mniej czasu. To ćwiczy automatyzację,
a nie wiedzę, i praktycznie nie występuje w aplikacjach do nauki.

Uruchom: python tools/plynnosc.py
"""

TOPICS = [
 {"id": "day", "level": "A1", "domain": "general", "emoji": "🌅",
  "pl": "Opowiedz o swoim wczorajszym dniu", "en": "Tell me about your day yesterday",
  "phrases": [["I got up at…", "Wstałem o…"], ["Then I…", "Potem…"],
              ["After that…", "Po tym…"], ["In the evening…", "Wieczorem…"],
              ["I was tired because…", "Byłem zmęczony, bo…"]],
  "hints": ["o której wstałeś", "co jadłeś", "gdzie byłeś", "kogo spotkałeś", "jak się czułeś"]},
 {"id": "job", "level": "A1", "domain": "work", "emoji": "🏭",
  "pl": "Opowiedz, na czym polega Twoja praca", "en": "Tell me about your job",
  "phrases": [["I work as a…", "Pracuję jako…"], ["My shift starts at…", "Moja zmiana zaczyna się o…"],
              ["I have to…", "Muszę…"], ["The hardest part is…", "Najtrudniejsze jest…"],
              ["I like it because…", "Lubię to, bo…"]],
  "hints": ["gdzie pracujesz", "co robisz w ciągu dnia", "z kim pracujesz", "co jest trudne", "co lubisz"]},
 {"id": "family", "level": "A1", "domain": "general", "emoji": "👨‍👩‍👧",
  "pl": "Opowiedz o swojej rodzinie", "en": "Tell me about your family",
  "phrases": [["I have…", "Mam…"], ["He / She is…", "On / Ona jest…"],
              ["We usually…", "Zwykle…"], ["My favourite…", "Mój ulubiony…"]],
  "hints": ["ile osób", "czym się zajmują", "gdzie mieszkają", "co robicie razem"]},
 {"id": "home", "level": "A1", "domain": "general", "emoji": "🏠",
  "pl": "Opisz miejsce, w którym mieszkasz", "en": "Describe the place where you live",
  "phrases": [["I live in…", "Mieszkam w…"], ["There is / There are…", "Jest / Są…"],
              ["It's near…", "To blisko…"], ["What I like most is…", "Najbardziej lubię…"]],
  "hints": ["miasto czy wieś", "ile pokoi", "co jest w okolicy", "co byś zmienił"]},
 {"id": "weekend", "level": "A2", "domain": "general", "emoji": "🎉",
  "pl": "Co robisz w weekend?", "en": "What do you do at the weekend?",
  "phrases": [["Usually I…", "Zwykle…"], ["Sometimes we…", "Czasem…"],
              ["Last weekend I…", "W zeszły weekend…"], ["Next weekend I'm going to…", "W przyszły weekend zamierzam…"]],
  "hints": ["sobota rano", "z kim spędzasz czas", "coś, co robisz zawsze", "plany"]},
 {"id": "trip", "level": "A2", "domain": "travel", "emoji": "✈️",
  "pl": "Opowiedz o wyjeździe, który pamiętasz", "en": "Tell me about a trip you remember",
  "phrases": [["We went to…", "Pojechaliśmy do…"], ["We stayed…", "Zatrzymaliśmy się…"],
              ["The best moment was…", "Najlepszy moment to…"], ["Next time I'd like to…", "Następnym razem chciałbym…"]],
  "hints": ["dokąd i z kim", "jak długo", "co było najlepsze", "co poszło źle"]},
 {"id": "problem", "level": "A2", "domain": "work", "emoji": "🔧",
  "pl": "Opowiedz o problemie w pracy i jak go rozwiązałeś", "en": "Tell me about a problem at work",
  "phrases": [["One day…", "Pewnego dnia…"], ["The problem was…", "Problem polegał na…"],
              ["So I decided to…", "Więc postanowiłem…"], ["In the end…", "W końcu…"]],
  "hints": ["co się stało", "dlaczego to był problem", "co zrobiłeś", "jak się skończyło"]},
 {"id": "food", "level": "A1", "domain": "general", "emoji": "🍲",
  "pl": "Opowiedz o jedzeniu, które lubisz", "en": "Tell me about food you like",
  "phrases": [["My favourite food is…", "Moje ulubione jedzenie to…"], ["I usually eat…", "Zwykle jem…"],
              ["I don't like…", "Nie lubię…"], ["You need…", "Potrzebujesz…"]],
  "hints": ["ulubione danie", "kto gotuje", "jak się to robi", "czego nie lubisz"]},
 {"id": "learning", "level": "A2", "domain": "general", "emoji": "📚",
  "pl": "Dlaczego uczysz się angielskiego?", "en": "Why are you learning English?",
  "phrases": [["I'm learning English because…", "Uczę się angielskiego, bo…"],
              ["It's difficult for me to…", "Trudno mi…"],
              ["I want to be able to…", "Chcę móc…"], ["In a year I hope…", "Za rok mam nadzieję…"]],
  "hints": ["powód", "co jest trudne", "gdzie używasz", "cel na rok"]},
 {"id": "person", "level": "A2", "domain": "general", "emoji": "🧑",
  "pl": "Opisz osobę, która jest dla Ciebie ważna", "en": "Describe a person who is important to you",
  "phrases": [["He / She is…", "On / Ona jest…"], ["We met…", "Poznaliśmy się…"],
              ["What I like about him / her…", "To, co w nim / niej lubię…"], ["He / She always…", "On / Ona zawsze…"]],
  "hints": ["kto to", "jak wygląda", "jaki ma charakter", "wspólne wspomnienie"]},
 {"id": "shopping", "level": "A1", "domain": "general", "emoji": "🛒",
  "pl": "Opowiedz o robieniu zakupów", "en": "Tell me about doing the shopping",
  "phrases": [["I usually go to…", "Zwykle chodzę do…"], ["I buy…", "Kupuję…"],
              ["It costs about…", "Kosztuje około…"], ["I don't like it when…", "Nie lubię, kiedy…"]],
  "hints": ["gdzie", "jak często", "co kupujesz", "ile wydajesz"]},
 {"id": "future", "level": "A2", "domain": "general", "emoji": "🔮",
  "pl": "Jakie masz plany na najbliższy rok?", "en": "What are your plans for the next year?",
  "phrases": [["I'm going to…", "Zamierzam…"], ["I hope to…", "Mam nadzieję…"],
              ["I'd like to…", "Chciałbym…"], ["It depends on…", "To zależy od…"]],
  "hints": ["praca", "nauka", "wyjazd", "coś prywatnego"]},
]

# Fragmenty do shadowingu — powtarzasz za lektorem z opóźnieniem pół sekundy.
# Krótkie, naturalne wypowiedzi z rytmem mowy codziennej.
PASSAGES = [
 {"id": "sh_intro", "level": "A1", "emoji": "👋", "name": "Przedstawienie się",
  "lines": [["Hi, my name is Tom.", "Cześć, mam na imię Tom."],
            ["I'm from Poland, but I live in England now.", "Jestem z Polski, ale teraz mieszkam w Anglii."],
            ["I work in a warehouse near Manchester.", "Pracuję w magazynie niedaleko Manchesteru."],
            ["I've been here for two years.", "Jestem tu od dwóch lat."],
            ["My English isn't perfect, but I'm learning.", "Mój angielski nie jest doskonały, ale się uczę."]]},
 {"id": "sh_day", "level": "A1", "emoji": "⏰", "name": "Zwykły dzień",
  "lines": [["I get up at half past five.", "Wstaję o wpół do szóstej."],
            ["I have a coffee and go to work.", "Piję kawę i jadę do pracy."],
            ["The shift starts at seven and finishes at three.", "Zmiana zaczyna się o siódmej i kończy o trzeciej."],
            ["After work I usually go shopping.", "Po pracy zwykle robię zakupy."],
            ["In the evening I'm too tired to do anything.", "Wieczorem jestem za bardzo zmęczony, żeby cokolwiek robić."]]},
 {"id": "sh_shop", "level": "A1", "emoji": "🛍", "name": "W sklepie",
  "lines": [["Excuse me, do you have this in a bigger size?", "Przepraszam, czy ma pan to w większym rozmiarze?"],
            ["I'm afraid we don't, sorry.", "Niestety nie, przykro mi."],
            ["Never mind. How much is this one?", "Nieważne. Ile kosztuje ten?"],
            ["It's twelve ninety-nine.", "Dwanaście dziewięćdziesiąt dziewięć."],
            ["OK, I'll take it. Can I pay by card?", "Dobrze, wezmę go. Mogę zapłacić kartą?"]]},
 {"id": "sh_work", "level": "A2", "emoji": "🏭", "name": "Rozmowa w pracy",
  "lines": [["Could you give me a hand with these boxes?", "Mógłbyś mi pomóc z tymi pudłami?"],
            ["Sure, where do you want them?", "Jasne, gdzie mam je postawić?"],
            ["Over there, next to the door, please.", "Tam, obok drzwi, proszę."],
            ["No problem. Anything else?", "Nie ma sprawy. Coś jeszcze?"],
            ["That's it, thanks a lot.", "To wszystko, wielkie dzięki."]]},
 {"id": "sh_doctor", "level": "A2", "emoji": "🏥", "name": "U lekarza",
  "lines": [["I'd like to make an appointment, please.", "Chciałbym umówić wizytę."],
            ["What seems to be the problem?", "Co panu dolega?"],
            ["I've had a headache for three days.", "Od trzech dni boli mnie głowa."],
            ["Have you taken anything for it?", "Brał pan coś na to?"],
            ["Only some painkillers, but they didn't help.", "Tylko leki przeciwbólowe, ale nie pomogły."]]},
 {"id": "sh_phone", "level": "A2", "emoji": "📞", "name": "Rozmowa telefoniczna",
  "lines": [["Hello, could I speak to Mr Brown, please?", "Dzień dobry, czy mogę rozmawiać z panem Brownem?"],
            ["I'm sorry, he's not available at the moment.", "Przykro mi, w tej chwili jest niedostępny."],
            ["Could you ask him to call me back?", "Mógłby pan poprosić, żeby oddzwonił?"],
            ["Of course. Can I take your number?", "Oczywiście. Mogę prosić o numer?"],
            ["Yes, it's oh seven double nine, three four one.", "Tak, to zero siedem dziewięć dziewięć, trzy cztery jeden."]]},
]

if __name__ == "__main__":
    import json, os
    d = {"topics": TOPICS, "passages": PASSAGES}
    p = os.path.join(os.path.dirname(__file__), "..", "data", "plynnosc")
    os.makedirs(p, exist_ok=True)
    json.dump(d, open(os.path.join(p, "plynnosc.json"), "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)
    print(f"płynność: {len(TOPICS)} tematów 4/3/2, {len(PASSAGES)} fragmentów do shadowingu")
