# -*- coding: utf-8 -*-
"""Zdania przykładowe do słówek (A1) — wzorzec: proste, z gramatyką z Podstaw (to be, present simple).
Uruchom: python tools/przyklady_a1.py — dopisuje pola example / example_pl do plików słownictwa."""
EX = {
 # ---- rodzina i ludzie
 "mother": ("My mother is a nurse.", "Moja mama jest pielęgniarką."),
 "father": ("My father works in a warehouse.", "Mój tata pracuje w magazynie."),
 "parents": ("My parents are at home.", "Moi rodzice są w domu."),
 "son": ("Their son is ten years old.", "Ich syn ma dziesięć lat."),
 "daughter": ("Our daughter likes music.", "Nasza córka lubi muzykę."),
 "brother": ("My brother is a driver.", "Mój brat jest kierowcą."),
 "sister": ("Her sister lives in London.", "Jej siostra mieszka w Londynie."),
 "grandmother": ("My grandmother is 80.", "Moja babcia ma 80 lat."),
 "grandfather": ("My grandfather has a big garden.", "Mój dziadek ma duży ogród."),
 "uncle": ("My uncle is a teacher.", "Mój wujek jest nauczycielem."),
 "aunt": ("My aunt lives near us.", "Moja ciocia mieszka blisko nas."),
 "cousin": ("My cousin is my best friend.", "Mój kuzyn jest moim najlepszym przyjacielem."),
 "husband": ("Her husband is a good cook.", "Jej mąż dobrze gotuje."),
 "wife": ("My wife works at night.", "Moja żona pracuje w nocy."),
 "baby": ("The baby is asleep.", "Niemowlę śpi."),
 "boy": ("The boy is my nephew.", "Ten chłopiec to mój bratanek."),
 "girl": ("The girl has a red bike.", "Dziewczynka ma czerwony rower."),
 "neighbour": ("Our neighbour is very friendly.", "Nasz sąsiad jest bardzo miły."),
 "guest": ("We have a guest tonight.", "Mamy dziś wieczorem gościa."),
 "stranger": ("Don't talk to strangers.", "Nie rozmawiaj z nieznajomymi."),
 "adult": ("Tickets for adults cost ten pounds.", "Bilety dla dorosłych kosztują dziesięć funtów."),
 "teenager": ("My son is a teenager now.", "Mój syn jest już nastolatkiem."),
 "people": ("There are many people here.", "Jest tu dużo ludzi."),
 "person": ("She is a kind person.", "Ona jest miłą osobą."),
 "nephew": ("My nephew is five.", "Mój bratanek ma pięć lat."),
 "niece": ("My niece loves animals.", "Moja siostrzenica kocha zwierzęta."),
 "grandson": ("Her grandson is a student.", "Jej wnuk jest studentem."),
 "granddaughter": ("Their granddaughter is two.", "Ich wnuczka ma dwa lata."),
 "mother-in-law": ("My mother-in-law is visiting us.", "Moja teściowa nas odwiedza."),
 "father-in-law": ("My father-in-law is a farmer.", "Mój teść jest rolnikiem."),
 "partner": ("This is my partner, Anna.", "To moja partnerka, Anna."),
 "girlfriend": ("His girlfriend is from Spain.", "Jego dziewczyna jest z Hiszpanii."),
 "boyfriend": ("Her boyfriend plays football.", "Jej chłopak gra w piłkę nożną."),
 "relative": ("We have relatives in Germany.", "Mamy krewnych w Niemczech."),
 "twins": ("They are twins.", "Oni są bliźniakami."),
 "only child": ("I am an only child.", "Jestem jedynakiem."),
 "widow": ("She is a widow.", "Ona jest wdową."),
 "engaged": ("We are engaged!", "Jesteśmy zaręczeni!"),
 "married": ("Are you married?", "Jesteś żonaty / zamężna?"),
 "divorced": ("My parents are divorced.", "Moi rodzice są rozwiedzeni."),
 "single": ("He is single.", "On jest kawalerem."),
 "birthday": ("My birthday is in May.", "Moje urodziny są w maju."),
 "wedding": ("The wedding is on Saturday.", "Ślub jest w sobotę."),
 "funeral": ("The funeral is tomorrow.", "Pogrzeb jest jutro."),
 "childhood": ("I had a happy childhood.", "Miałem szczęśliwe dzieciństwo."),
 "generation": ("My generation likes phones.", "Moje pokolenie lubi telefony."),
 "elderly": ("Elderly people need help.", "Osoby starsze potrzebują pomocy."),
 "landlady": ("My landlady lives downstairs.", "Właścicielka mieszkania mieszka na dole."),
 "classmate": ("Tom is my classmate.", "Tom jest moim kolegą z klasy."),
 "teammate": ("My teammates are great.", "Moi koledzy z zespołu są świetni."),
 "crowd": ("There is a big crowd outside.", "Na zewnątrz jest wielki tłum."),
 "group": ("We work in a group of five.", "Pracujemy w pięcioosobowej grupie."),
 # ---- kolory
 "red": ("The bus is red.", "Autobus jest czerwony."),
 "blue": ("My car is blue.", "Mój samochód jest niebieski."),
 "green": ("The grass is green.", "Trawa jest zielona."),
 "yellow": ("Bananas are yellow.", "Banany są żółte."),
 "black": ("I have a black jacket.", "Mam czarną kurtkę."),
 "white": ("The walls are white.", "Ściany są białe."),
 "grey": ("The sky is grey today.", "Niebo jest dziś szare."),
 "brown": ("Her eyes are brown.", "Jej oczy są brązowe."),
 "pink": ("The baby's room is pink.", "Pokój dziecka jest różowy."),
 "purple": ("She likes purple flowers.", "Ona lubi fioletowe kwiaty."),
 "orange (colour)": ("The safety vest is orange.", "Kamizelka odblaskowa jest pomarańczowa."),
 "gold": ("Her ring is gold.", "Jej pierścionek jest złoty."),
 "silver": ("The car is silver.", "Samochód jest srebrny."),
 "dark": ("It is dark outside.", "Na zewnątrz jest ciemno."),
 "light (colour)": ("I want a light blue shirt.", "Chcę jasnoniebieską koszulę."),
 "navy blue": ("The uniform is navy blue.", "Mundur jest granatowy."),
 "sky blue": ("The room is sky blue.", "Pokój jest błękitny."),
 "turquoise": ("The sea is turquoise here.", "Morze jest tu turkusowe."),
 "beige": ("The sofa is beige.", "Kanapa jest beżowa."),
 "cream (colour)": ("The kitchen is cream.", "Kuchnia jest kremowa."),
 "violet": ("Violet is my favourite colour.", "Fioletowy to mój ulubiony kolor."),
 "lime": ("The T-shirt is lime.", "Koszulka jest limonkowa."),
 "olive": ("He has an olive jacket.", "On ma oliwkową kurtkę."),
 "bright": ("The light is very bright.", "Światło jest bardzo jasne."),
 "pale": ("You look pale. Are you ill?", "Wyglądasz blado. Jesteś chory?"),
 "colourful": ("The market is colourful.", "Targ jest kolorowy."),
 "plain": ("I want a plain white T-shirt.", "Chcę zwykłą białą koszulkę."),
 "striped": ("He wears a striped shirt.", "On nosi koszulę w paski."),
 "spotted": ("Her dress is spotted.", "Jej sukienka jest w kropki."),
 "checked": ("I like checked shirts.", "Lubię koszule w kratę."),
 "shiny": ("The floor is shiny.", "Podłoga jest błyszcząca."),
 "matt": ("The paint is matt.", "Farba jest matowa."),
}

# ======================= pozostałe tematy A1 (v3.3) =======================
EX.update({
 # ---- przymiotniki
 "big": ("We have a big kitchen.", "Mamy dużą kuchnię."),
 "small": ("The room is small.", "Pokój jest mały."),
 "long": ("It is a long day.", "To długi dzień."),
 "short": ("My brother is short.", "Mój brat jest niski."),
 "tall": ("My father is very tall.", "Mój tata jest bardzo wysoki."),
 "wide": ("The road is wide.", "Droga jest szeroka."),
 "narrow": ("The street is narrow.", "Ulica jest wąska."),
 "thick": ("This book is thick.", "Ta książka jest gruba."),
 "thin": ("The walls are thin.", "Ściany są cienkie."),
 "deep": ("The river is deep here.", "Rzeka jest tu głęboka."),
 "full": ("The bus is full.", "Autobus jest pełny."),
 "empty": ("The box is empty.", "Pudełko jest puste."),
 "clean": ("The kitchen is clean.", "Kuchnia jest czysta."),
 "dirty": ("My shoes are dirty.", "Moje buty są brudne."),
 "wet": ("The floor is wet.", "Podłoga jest mokra."),
 "dry": ("The towel is dry.", "Ręcznik jest suchy."),
 "hot": ("The soup is hot.", "Zupa jest gorąca."),
 "cold": ("The water is cold.", "Woda jest zimna."),
 "new": ("I have a new phone.", "Mam nowy telefon."),
 "old": ("This car is old.", "Ten samochód jest stary."),
 "young": ("She is young.", "Ona jest młoda."),
 "modern": ("It is a modern flat.", "To nowoczesne mieszkanie."),
 "cheap": ("The tickets are cheap.", "Bilety są tanie."),
 "expensive": ("This coat is expensive.", "Ten płaszcz jest drogi."),
 "rich": ("They are rich.", "Oni są bogaci."),
 "poor": ("He is poor but happy.", "On jest biedny, ale szczęśliwy."),
 "easy": ("The test is easy.", "Test jest łatwy."),
 "difficult": ("English is difficult.", "Angielski jest trudny."),
 "important": ("This is important.", "To jest ważne."),
 "necessary": ("Is it necessary?", "Czy to konieczne?"),
 "possible": ("It is possible.", "To możliwe."),
 "impossible": ("That is impossible!", "To niemożliwe!"),
 "ready": ("Dinner is ready.", "Obiad jest gotowy."),
 "busy": ("I am busy today.", "Jestem dziś zajęty."),
 "free (available)": ("Are you free tomorrow?", "Jesteś jutro wolny?"),
 "open (adj)": ("The shop is open.", "Sklep jest otwarty."),
 "closed": ("The bank is closed.", "Bank jest zamknięty."),
 "loud": ("The music is too loud.", "Muzyka jest za głośna."),
 "silent": ("The house is silent at night.", "Dom jest cichy w nocy."),
 "fast": ("This car is fast.", "Ten samochód jest szybki."),
 "slow": ("The bus is slow.", "Autobus jest wolny."),
 "dangerous": ("This road is dangerous.", "Ta droga jest niebezpieczna."),
 "safe (adj)": ("It is safe here.", "Tu jest bezpiecznie."),
 "useful": ("This app is useful.", "Ta aplikacja jest przydatna."),
 "useless": ("This old map is useless.", "Ta stara mapa jest bezużyteczna."),
 "similar": ("Our jobs are similar.", "Nasze prace są podobne."),
 "different": ("The two rooms are different.", "Te dwa pokoje są różne."),
 "same": ("We have the same car.", "Mamy taki sam samochód."),
 "correct": ("Your answer is correct.", "Twoja odpowiedź jest poprawna."),
 "wrong": ("This number is wrong.", "Ten numer jest zły."),
 # ---- liczebniki
 "zero": ("The temperature is zero.", "Temperatura wynosi zero."),
 "one": ("I have one brother.", "Mam jednego brata."),
 "two": ("We have two cats.", "Mamy dwa koty."),
 "three": ("The lesson is three hours long.", "Lekcja trwa trzy godziny."),
 "four": ("There are four chairs.", "Są cztery krzesła."),
 "five": ("I work five days a week.", "Pracuję pięć dni w tygodniu."),
 "six": ("The shift starts at six.", "Zmiana zaczyna się o szóstej."),
 "seven": ("A week has seven days.", "Tydzień ma siedem dni."),
 "eight": ("I sleep eight hours.", "Śpię osiem godzin."),
 "nine": ("The shop opens at nine.", "Sklep otwiera się o dziewiątej."),
 "ten": ("Ten people work here.", "Pracuje tu dziesięć osób."),
 "eleven": ("My son is eleven.", "Mój syn ma jedenaście lat."),
 "twelve": ("A year has twelve months.", "Rok ma dwanaście miesięcy."),
 "thirteen": ("Room thirteen is free.", "Pokój trzynaście jest wolny."),
 "fourteen": ("The bus is fourteen minutes late.", "Autobus jest spóźniony czternaście minut."),
 "fifteen": ("The break is fifteen minutes.", "Przerwa trwa piętnaście minut."),
 "sixteen": ("My daughter is sixteen.", "Moja córka ma szesnaście lat."),
 "seventeen": ("Take bus number seventeen.", "Weź autobus numer siedemnaście."),
 "eighteen": ("You must be eighteen.", "Musisz mieć osiemnaście lat."),
 "nineteen": ("It costs nineteen pounds.", "To kosztuje dziewiętnaście funtów."),
 "twenty": ("I am twenty years old.", "Mam dwadzieścia lat."),
 "thirty": ("Thirty people are waiting.", "Trzydzieści osób czeka."),
 "forty": ("My mother is forty.", "Moja mama ma czterdzieści lat."),
 "fifty": ("The box weighs fifty kilos.", "Pudło waży pięćdziesiąt kilo."),
 "sixty": ("An hour has sixty minutes.", "Godzina ma sześćdziesiąt minut."),
 "seventy": ("My grandfather is seventy.", "Mój dziadek ma siedemdziesiąt lat."),
 "eighty": ("The ticket is eighty pounds.", "Bilet kosztuje osiemdziesiąt funtów."),
 "ninety": ("Ninety percent is very good.", "Dziewięćdziesiąt procent to bardzo dobrze."),
 "hundred": ("There are a hundred boxes.", "Jest sto pudeł."),
 "thousand": ("The car costs five thousand pounds.", "Samochód kosztuje pięć tysięcy funtów."),
 "million": ("London has nine million people.", "Londyn ma dziewięć milionów ludzi."),
 "first": ("This is my first day.", "To mój pierwszy dzień."),
 "second": ("Take the second door.", "Wejdź w drugie drzwi."),
 "third": ("I live on the third floor.", "Mieszkam na trzecim piętrze."),
 "fourth": ("It is the fourth of May.", "Jest czwarty maja."),
 "fifth": ("This is my fifth coffee today.", "To moja piąta kawa dzisiaj."),
 "tenth": ("It is my tenth year here.", "To mój dziesiąty rok tutaj."),
 "half": ("Half of the team is ill.", "Połowa zespołu jest chora."),
 "quarter": ("It is a quarter past two.", "Jest kwadrans po drugiej."),
 "double": ("I want a double room.", "Chcę pokój dwuosobowy."),
 # ---- kalendarz
 "Monday": ("The meeting is on Monday.", "Spotkanie jest w poniedziałek."),
 "Tuesday": ("I have English on Tuesday.", "Mam angielski we wtorek."),
 "Wednesday": ("Wednesday is my day off.", "Środa to mój dzień wolny."),
 "Thursday": ("We finish early on Thursday.", "W czwartek kończymy wcześniej."),
 "Friday": ("Friday is my favourite day.", "Piątek to mój ulubiony dzień."),
 "Saturday": ("Do you work on Saturday?", "Pracujesz w sobotę?"),
 "Sunday": ("The shop is closed on Sunday.", "Sklep jest zamknięty w niedzielę."),
 "January": ("It is cold in January.", "W styczniu jest zimno."),
 "February": ("February is a short month.", "Luty to krótki miesiąc."),
 "March": ("Spring starts in March.", "Wiosna zaczyna się w marcu."),
 "April": ("My birthday is in April.", "Moje urodziny są w kwietniu."),
 "May": ("We have a holiday in May.", "W maju mamy wolne."),
 "June": ("School ends in June.", "Szkoła kończy się w czerwcu."),
 "July": ("July is very hot.", "Lipiec jest bardzo gorący."),
 "August": ("We go on holiday in August.", "W sierpniu jedziemy na wakacje."),
 "September": ("Work starts again in September.", "Praca zaczyna się znów we wrześniu."),
 "October": ("The leaves fall in October.", "Liście spadają w październiku."),
 "November": ("November is grey and wet.", "Listopad jest szary i mokry."),
 "December": ("Christmas is in December.", "Boże Narodzenie jest w grudniu."),
 "spring": ("I like spring.", "Lubię wiosnę."),
 "summer": ("Summer is short in Poland.", "Lato w Polsce jest krótkie."),
 "autumn": ("Autumn is beautiful here.", "Jesień jest tu piękna."),
 "winter": ("Winter is cold and dark.", "Zima jest zimna i ciemna."),
 "today": ("I am at home today.", "Dziś jestem w domu."),
 "tomorrow": ("See you tomorrow!", "Do jutra!"),
 "yesterday": ("I was ill yesterday.", "Wczoraj byłem chory."),
 "weekend": ("What do you do at the weekend?", "Co robisz w weekend?"),
 "midnight": ("The shift ends at midnight.", "Zmiana kończy się o północy."),
 "noon": ("Lunch is at noon.", "Lunch jest w południe."),
 "date": ("What is the date today?", "Jaka jest dziś data?"),
 "hour": ("The break is one hour.", "Przerwa trwa godzinę."),
 "minute": ("Wait a minute, please.", "Poczekaj minutę, proszę."),
 "second": ("Just a second!", "Sekundkę!"),
 "o'clock": ("It is seven o'clock.", "Jest siódma."),
 "quarter past": ("It is quarter past nine.", "Jest kwadrans po dziewiątej."),
 "half past": ("The bus leaves at half past six.", "Autobus odjeżdża o wpół do siódmej."),
 "quarter to": ("It is quarter to five.", "Jest za kwadrans piąta."),
 "morning shift": ("I am on the morning shift this week.", "W tym tygodniu jestem na porannej zmianie."),
 "night shift": ("The night shift starts at ten.", "Nocna zmiana zaczyna się o dziesiątej."),
 "afternoon": ("I am free in the afternoon.", "Po południu jestem wolny."),
 "tonight": ("We are going out tonight.", "Dziś wieczorem wychodzimy."),
 "the day after tomorrow": ("The delivery is the day after tomorrow.", "Dostawa jest pojutrze."),
 "the day before yesterday": ("I saw him the day before yesterday.", "Widziałem go przedwczoraj."),
 "last week": ("I was in London last week.", "W zeszłym tygodniu byłem w Londynie."),
 "next month": ("We move next month.", "Przeprowadzamy się w przyszłym miesiącu."),
 "public holiday": ("Monday is a public holiday.", "Poniedziałek jest dniem wolnym od pracy."),
 "deadline": ("The deadline is on Friday.", "Termin jest w piątek."),
 "schedule (time)": ("Check the schedule, please.", "Sprawdź harmonogram, proszę."),
 "appointment (time)": ("I have an appointment at three.", "Mam umówione spotkanie o trzeciej."),
 "early": ("I get up early.", "Wstaję wcześnie."),
 "late": ("Sorry, I am late.", "Przepraszam za spóźnienie."),
 "on time": ("The train is on time.", "Pociąg jest punktualnie."),
 "soon": ("See you soon!", "Do zobaczenia wkrótce!"),
 "already": ("The bus is already here.", "Autobus już tu jest."),
 "still": ("He is still at work.", "On nadal jest w pracy."),
 "yet": ("Dinner is not ready yet.", "Obiad nie jest jeszcze gotowy."),
 "recently": ("I was in Poland recently.", "Byłem ostatnio w Polsce."),
 "nowadays": ("Nowadays everyone has a phone.", "Obecnie każdy ma telefon."),
 # ---- jedzenie
 "apple": ("I eat an apple every day.", "Codziennie jem jabłko."),
 "banana": ("Bananas are cheap here.", "Banany są tu tanie."),
 "orange": ("This orange is sweet.", "Ta pomarańcza jest słodka."),
 "lemon": ("I want tea with lemon.", "Chcę herbatę z cytryną."),
 "tomato": ("Tomatoes are red.", "Pomidory są czerwone."),
 "potato": ("We have potatoes for dinner.", "Na obiad mamy ziemniaki."),
 "onion": ("I don't like onion.", "Nie lubię cebuli."),
 "carrot": ("Rabbits eat carrots.", "Króliki jedzą marchewki."),
 "cucumber": ("The salad has cucumber in it.", "W sałatce jest ogórek."),
 "cheese": ("I want a cheese sandwich.", "Chcę kanapkę z serem."),
 "butter": ("Bread with butter is simple and good.", "Chleb z masłem jest prosty i dobry."),
 "egg": ("I eat two eggs for breakfast.", "Jem dwa jajka na śniadanie."),
 "meat": ("My sister doesn't eat meat.", "Moja siostra nie je mięsa."),
 "chicken (food)": ("We have chicken and rice.", "Mamy kurczaka z ryżem."),
 "pork": ("Pork is popular in Poland.", "Wieprzowina jest popularna w Polsce."),
 "beef": ("This beef is very good.", "Ta wołowina jest bardzo dobra."),
 "fish (food)": ("We eat fish on Friday.", "W piątek jemy rybę."),
 "rice": ("Rice is cheap and healthy.", "Ryż jest tani i zdrowy."),
 "pasta": ("The children love pasta.", "Dzieci uwielbiają makaron."),
 "soup": ("The soup is hot.", "Zupa jest gorąca."),
 "salad": ("I want a salad, please.", "Poproszę sałatkę."),
 "sandwich": ("I have a sandwich for lunch.", "Na lunch mam kanapkę."),
 "pizza": ("Pizza is my favourite food.", "Pizza to moje ulubione jedzenie."),
 "cake": ("The cake is delicious.", "Ciasto jest pyszne."),
 "cookie": ("Do you want a cookie?", "Chcesz ciastko?"),
 "chocolate": ("I love chocolate.", "Kocham czekoladę."),
 "sugar": ("No sugar in my coffee, please.", "Bez cukru w kawie, proszę."),
 "salt": ("Pass me the salt, please.", "Podaj mi sól, proszę."),
 "pepper": ("The soup needs pepper.", "Zupa potrzebuje pieprzu."),
 "oil": ("Fry it in oil.", "Usmaż to na oleju."),
 "juice": ("I drink orange juice.", "Piję sok pomarańczowy."),
 "beer": ("Do you want a beer?", "Chcesz piwo?"),
 "wine": ("We drink wine at dinner.", "Pijemy wino do obiadu."),
 "breakfast": ("Breakfast is at seven.", "Śniadanie jest o siódmej."),
 "lunch": ("Lunch is at twelve.", "Lunch jest o dwunastej."),
 "dinner": ("Dinner is ready!", "Obiad gotowy!"),
 "snack": ("I have a snack at ten.", "O dziesiątej mam przekąskę."),
 "meal": ("It is a big meal.", "To duży posiłek."),
 "flour": ("We need flour for the cake.", "Potrzebujemy mąki na ciasto."),
 "honey": ("Tea with honey is good for you.", "Herbata z miodem jest zdrowa."),
 "jam": ("I like strawberry jam.", "Lubię dżem truskawkowy."),
 "yoghurt": ("I eat yoghurt every morning.", "Codziennie rano jem jogurt."),
 "cream": ("Coffee with cream, please.", "Kawa ze śmietanką, proszę."),
 "sausage": ("Polish sausage is famous.", "Polska kiełbasa jest sławna."),
 "ham": ("A ham sandwich, please.", "Poproszę kanapkę z szynką."),
 "bacon": ("Eggs and bacon for breakfast.", "Jajka z boczkiem na śniadanie."),
 "fish fillet": ("The fish fillet is fresh.", "Filet rybny jest świeży."),
 "soup spoon": ("Take a soup spoon.", "Weź łyżkę do zupy."),
 "garlic": ("The sauce has a lot of garlic.", "W sosie jest dużo czosnku."),
 "mushroom": ("I like mushroom soup.", "Lubię zupę grzybową."),
 "pepper (vegetable)": ("Red pepper is sweet.", "Czerwona papryka jest słodka."),
 "cabbage": ("Cabbage is cheap in winter.", "Kapusta jest tania zimą."),
 "lettuce": ("Wash the lettuce.", "Umyj sałatę."),
 "bean": ("Beans are healthy.", "Fasola jest zdrowa."),
 "pea": ("The soup has peas in it.", "W zupie jest groszek."),
 "corn": ("I like corn on pizza.", "Lubię kukurydzę na pizzy."),
 "strawberry": ("Strawberries are sweet in June.", "Truskawki są słodkie w czerwcu."),
 "raspberry": ("My garden has raspberries.", "W moim ogrodzie są maliny."),
 "cherry": ("The cherry cake is great.", "Ciasto wiśniowe jest świetne."),
 "pear": ("This pear is soft.", "Ta gruszka jest miękka."),
 "plum": ("Plums are ripe in August.", "Śliwki dojrzewają w sierpniu."),
 "grape": ("I buy grapes at the market.", "Kupuję winogrona na targu."),
 "watermelon": ("Watermelon is good in summer.", "Arbuz jest dobry latem."),
 "nut": ("I eat nuts as a snack.", "Jem orzechy jako przekąskę."),
 "raisin": ("The cake has raisins in it.", "W cieście są rodzynki."),
 "pancake": ("We eat pancakes on Sunday.", "W niedzielę jemy naleśniki."),
 "porridge": ("Porridge is a healthy breakfast.", "Owsianka to zdrowe śniadanie."),
 "cereal": ("The children eat cereal with milk.", "Dzieci jedzą płatki z mlekiem."),
 "toast": ("Two slices of toast, please.", "Dwie kromki tostu, proszę."),
 "roll": ("A roll with butter, please.", "Bułka z masłem, proszę."),
 "pastry": ("The pastry is fresh.", "Ciastko jest świeże."),
 "ice cream": ("Ice cream is good in summer.", "Lody są dobre latem."),
 "dessert": ("What is for dessert?", "Co jest na deser?"),
 "sauce": ("Pasta with tomato sauce.", "Makaron z sosem pomidorowym."),
 "vinegar": ("The salad needs vinegar.", "Sałatka potrzebuje octu."),
 "spice": ("I like spices in my food.", "Lubię przyprawy w jedzeniu."),
 "recipe": ("This is my mother's recipe.", "To przepis mojej mamy."),
 "taste": ("The taste is strange.", "Smak jest dziwny."),
 "fresh": ("The bread is fresh.", "Chleb jest świeży."),
 "frozen": ("We have frozen pizza.", "Mamy mrożoną pizzę."),
 "boiled": ("I like boiled eggs.", "Lubię gotowane jajka."),
 "fried": ("Fried chicken is not healthy.", "Smażony kurczak nie jest zdrowy."),
 "baked": ("Baked potatoes are great.", "Pieczone ziemniaki są świetne."),
 "hungry": ("I am hungry.", "Jestem głodny."),
 "thirsty": ("Are you thirsty?", "Chce ci się pić?"),
 "delicious": ("The pizza is delicious.", "Pizza jest pyszna."),
})

EX.update({
 # ---- dom
 "living room": ("We watch TV in the living room.", "Oglądamy telewizję w salonie."),
 "bedroom": ("My bedroom is small.", "Moja sypialnia jest mała."),
 "bathroom": ("The bathroom is upstairs.", "Łazienka jest na górze."),
 "toilet": ("Where is the toilet?", "Gdzie jest toaleta?"),
 "garage": ("The car is in the garage.", "Samochód jest w garażu."),
 "garden": ("We have a small garden.", "Mamy mały ogród."),
 "stairs": ("Be careful on the stairs.", "Uważaj na schodach."),
 "roof": ("The roof is old.", "Dach jest stary."),
 "ceiling": ("The ceiling is white.", "Sufit jest biały."),
 "lamp": ("Turn on the lamp, please.", "Włącz lampę, proszę."),
 "mirror": ("There is a mirror in the hall.", "W przedpokoju jest lustro."),
 "towel": ("Where is my towel?", "Gdzie jest mój ręcznik?"),
 "soap": ("We need soap.", "Potrzebujemy mydła."),
 "shower": ("I take a shower every morning.", "Codziennie rano biorę prysznic."),
 "bath": ("The bath is full.", "Wanna jest pełna."),
 "fridge": ("The milk is in the fridge.", "Mleko jest w lodówce."),
 "cooker": ("The cooker is new.", "Kuchenka jest nowa."),
 "oven": ("The cake is in the oven.", "Ciasto jest w piekarniku."),
 "washing machine": ("The washing machine is broken.", "Pralka jest zepsuta."),
 "sink": ("The plates are in the sink.", "Talerze są w zlewie."),
 "cup": ("I want a cup of tea.", "Chcę filiżankę herbaty."),
 "glass": ("Can I have a glass of water?", "Mogę prosić szklankę wody?"),
 "plate": ("Put the plate on the table.", "Postaw talerz na stole."),
 "bowl": ("The soup is in a bowl.", "Zupa jest w misce."),
 "knife": ("This knife is sharp.", "Ten nóż jest ostry."),
 "fork": ("I need a fork.", "Potrzebuję widelca."),
 "spoon": ("Use a spoon for the soup.", "Użyj łyżki do zupy."),
 "pot": ("The pot is on the cooker.", "Garnek jest na kuchence."),
 "pan": ("Put the eggs in the pan.", "Włóż jajka na patelnię."),
 "bin": ("The bin is full.", "Kosz jest pełny."),
 "shelf": ("The books are on the shelf.", "Książki są na półce."),
 "carpet": ("The carpet is dirty.", "Dywan jest brudny."),
 "furniture": ("The furniture is old.", "Meble są stare."),
 "sofa": ("The cat sleeps on the sofa.", "Kot śpi na kanapie."),
 "armchair": ("My father sits in the armchair.", "Mój tata siedzi w fotelu."),
 "wardrobe": ("My clothes are in the wardrobe.", "Moje ubrania są w szafie."),
 "drawer": ("The keys are in the drawer.", "Klucze są w szufladzie."),
 "cupboard": ("The cups are in the cupboard.", "Kubki są w szafce."),
 "curtain": ("Close the curtains, please.", "Zasuń zasłony, proszę."),
 "blanket": ("I need another blanket.", "Potrzebuję kolejnego koca."),
 "pillow": ("This pillow is too soft.", "Ta poduszka jest za miękka."),
 "sheet": ("The sheets are clean.", "Prześcieradła są czyste."),
 "mattress": ("The mattress is new.", "Materac jest nowy."),
 "heater": ("Turn on the heater.", "Włącz grzejnik."),
 "air conditioner": ("The air conditioner is loud.", "Klimatyzacja jest głośna."),
 "socket": ("Is there a socket here?", "Czy jest tu gniazdko?"),
 "switch": ("The switch is near the door.", "Włącznik jest przy drzwiach."),
 "bulb": ("The bulb is broken.", "Żarówka jest przepalona."),
 "candle": ("Light a candle.", "Zapal świecę."),
 "clock": ("The clock is slow.", "Zegar się spóźnia."),
 "vacuum cleaner": ("The vacuum cleaner is in the cupboard.", "Odkurzacz jest w szafce."),
 "iron": ("The iron is hot.", "Żelazko jest gorące."),
 "kettle": ("Put the kettle on.", "Nastaw czajnik."),
 "microwave": ("Heat it in the microwave.", "Podgrzej to w mikrofalówce."),
 "dishwasher": ("The dishwasher is full.", "Zmywarka jest pełna."),
 "freezer": ("The meat is in the freezer.", "Mięso jest w zamrażarce."),
 "tap": ("The tap is dripping.", "Kran cieknie."),
 "pipe": ("The pipe is broken.", "Rura jest pęknięta."),
 "lock": ("The lock is old.", "Zamek jest stary."),
 "doorbell": ("The doorbell doesn't work.", "Dzwonek do drzwi nie działa."),
 "balcony": ("We have coffee on the balcony.", "Pijemy kawę na balkonie."),
 "basement": ("The bikes are in the basement.", "Rowery są w piwnicy."),
 "attic": ("The old boxes are in the attic.", "Stare pudła są na strychu."),
 "fence": ("The fence is white.", "Płot jest biały."),
 "gate (garden)": ("Close the gate, please.", "Zamknij furtkę, proszę."),
 "rent (housing)": ("The rent is high here.", "Czynsz jest tu wysoki."),
 "landlord": ("My landlord is nice.", "Mój właściciel mieszkania jest miły."),
 "neighbourhood": ("This is a quiet neighbourhood.", "To spokojna okolica."),
 "cleaning": ("Cleaning takes two hours.", "Sprzątanie zajmuje dwie godziny."),
 "rubbish": ("Take out the rubbish, please.", "Wynieś śmieci, proszę."),
 "laundry": ("I do the laundry on Sunday.", "Piorę w niedzielę."),
 "tidy": ("My room is tidy.", "Mój pokój jest posprzątany."),
 # ---- ubrania
 "shirt": ("My shirt is white.", "Moja koszula jest biała."),
 "t-shirt": ("He wears a black t-shirt.", "On nosi czarną koszulkę."),
 "trousers": ("These trousers are too long.", "Te spodnie są za długie."),
 "jeans": ("I wear jeans every day.", "Codziennie noszę dżinsy."),
 "shorts": ("Shorts are good in summer.", "Krótkie spodenki są dobre latem."),
 "skirt": ("She has a blue skirt.", "Ona ma niebieską spódnicę."),
 "jacket": ("Take your jacket, it is cold.", "Weź kurtkę, jest zimno."),
 "coat": ("My coat is in the car.", "Mój płaszcz jest w samochodzie."),
 "sweater": ("This sweater is warm.", "Ten sweter jest ciepły."),
 "sock": ("I need clean socks.", "Potrzebuję czystych skarpetek."),
 "boot": ("My boots are dirty.", "Moje buty są brudne."),
 "trainers": ("I run in old trainers.", "Biegam w starych butach sportowych."),
 "hat": ("Wear a hat, it is cold.", "Załóż czapkę, jest zimno."),
 "cap": ("He always wears a cap.", "On zawsze nosi czapkę z daszkiem."),
 "glove": ("I lost one glove.", "Zgubiłem jedną rękawiczkę."),
 "scarf": ("This scarf is a present.", "Ten szalik to prezent."),
 "belt": ("I need a new belt.", "Potrzebuję nowego paska."),
 "pocket": ("The keys are in my pocket.", "Klucze są w mojej kieszeni."),
 "button": ("A button is missing.", "Brakuje guzika."),
 "suit": ("He wears a suit at work.", "On nosi garnitur w pracy."),
 "tie": ("I don't like ties.", "Nie lubię krawatów."),
 "blouse": ("Her blouse is pink.", "Jej bluzka jest różowa."),
 "hoodie": ("My son wears a hoodie.", "Mój syn nosi bluzę z kapturem."),
 "underwear": ("Pack some underwear.", "Spakuj trochę bielizny."),
 "pyjamas": ("The children are in pyjamas.", "Dzieci są w piżamach."),
 "swimsuit": ("Take your swimsuit.", "Weź strój kąpielowy."),
 "raincoat": ("A raincoat is useful here.", "Płaszcz przeciwdeszczowy jest tu przydatny."),
 "gloves (work)": ("Wear gloves in the warehouse.", "Noś rękawice w magazynie."),
 "helmet": ("A helmet is necessary here.", "Kask jest tu konieczny."),
 "goggles": ("Put on the goggles.", "Załóż gogle ochronne."),
 "earplugs": ("The machines are loud — use earplugs.", "Maszyny są głośne — użyj zatyczek."),
 "high-vis vest": ("Every worker has a high-vis vest.", "Każdy pracownik ma kamizelkę odblaskową."),
 "uniform": ("The uniform is navy blue.", "Mundur jest granatowy."),
 "size": ("What size do you wear?", "Jaki nosisz rozmiar?"),
 "sleeve": ("The sleeve is too short.", "Rękaw jest za krótki."),
 "collar": ("The collar is dirty.", "Kołnierz jest brudny."),
 "zip": ("The zip is broken.", "Zamek jest zepsuty."),
 "shoelace": ("Your shoelace is loose.", "Twoje sznurowadło jest rozwiązane."),
 "jewellery": ("No jewellery at work, please.", "Bez biżuterii w pracy, proszę."),
 "ring": ("She wears a gold ring.", "Ona nosi złoty pierścionek."),
 "watch (object)": ("My watch is slow.", "Mój zegarek się spóźnia."),
 "umbrella": ("Take an umbrella, it is raining.", "Weź parasol, pada."),
 "backpack": ("My backpack is heavy.", "Mój plecak jest ciężki."),
 "wallet": ("I lost my wallet.", "Zgubiłem portfel."),
 "handbag": ("Her handbag is new.", "Jej torebka jest nowa."),
 "wear out clothes": ("Children wear out clothes fast.", "Dzieci szybko znoszą ubrania."),
 "fit (clothes)": ("These shoes don't fit me.", "Te buty na mnie nie pasują."),
 "tight": ("These jeans are too tight.", "Te dżinsy są za obcisłe."),
 "loose": ("The shirt is loose.", "Koszula jest luźna."),
 # ---- zwierzęta
 "dog": ("My dog is very friendly.", "Mój pies jest bardzo przyjazny."),
 "cat": ("The cat is on the sofa.", "Kot jest na kanapie."),
 "bird": ("A bird is singing.", "Ptak śpiewa."),
 "fish": ("We have three fish.", "Mamy trzy rybki."),
 "horse": ("The horse is big and strong.", "Koń jest duży i silny."),
 "cow": ("Cows give us milk.", "Krowy dają nam mleko."),
 "pig": ("Pigs are clever animals.", "Świnie to mądre zwierzęta."),
 "sheep": ("The sheep are in the field.", "Owce są na polu."),
 "chicken": ("We have ten chickens.", "Mamy dziesięć kur."),
 "duck": ("The ducks are on the water.", "Kaczki są na wodzie."),
 "rabbit": ("My daughter has a rabbit.", "Moja córka ma królika."),
 "mouse": ("There is a mouse in the kitchen.", "W kuchni jest mysz."),
 "rat": ("Rats live near the bins.", "Szczury żyją przy śmietnikach."),
 "bear": ("Bears live in the forest.", "Niedźwiedzie żyją w lesie."),
 "wolf": ("The wolf is grey.", "Wilk jest szary."),
 "fox": ("A fox is in the garden.", "W ogrodzie jest lis."),
 "deer": ("We saw a deer this morning.", "Dziś rano widzieliśmy jelenia."),
 "lion": ("The lion is sleeping.", "Lew śpi."),
 "tiger": ("Tigers are orange and black.", "Tygrysy są pomarańczowo-czarne."),
 "elephant": ("The elephant is very big.", "Słoń jest bardzo duży."),
 "giraffe": ("A giraffe has a long neck.", "Żyrafa ma długą szyję."),
 "monkey": ("The monkey is funny.", "Małpa jest zabawna."),
 "snake": ("I am afraid of snakes.", "Boję się węży."),
 "spider": ("There is a spider on the wall.", "Na ścianie jest pająk."),
 "bee": ("Bees make honey.", "Pszczoły robią miód."),
 "fly": ("There is a fly in my soup.", "W mojej zupie jest mucha."),
 "ant": ("The ants are in the kitchen.", "Mrówki są w kuchni."),
 "frog": ("The frog is green.", "Żaba jest zielona."),
 "goat": ("The goat eats everything.", "Koza je wszystko."),
 "donkey": ("The donkey is small.", "Osioł jest mały."),
 "goose": ("The goose is loud.", "Gęś jest głośna."),
 "turkey": ("We eat turkey at Christmas.", "Na święta jemy indyka."),
 "bull": ("The bull is dangerous.", "Byk jest niebezpieczny."),
 "calf": ("The calf is one week old.", "Cielę ma tydzień."),
 "lamb": ("The lamb is with its mother.", "Jagnię jest przy matce."),
 "puppy": ("Our puppy is three months old.", "Nasz szczeniak ma trzy miesiące."),
 "kitten": ("The kitten is very small.", "Kociak jest bardzo mały."),
 "hen": ("The hen has six eggs.", "Kura ma sześć jajek."),
 "rooster": ("The rooster wakes me up.", "Kogut mnie budzi."),
 "pigeon": ("Pigeons are everywhere in the city.", "Gołębie są wszędzie w mieście."),
 "owl": ("The owl hunts at night.", "Sowa poluje w nocy."),
 "eagle": ("The eagle is a big bird.", "Orzeł to duży ptak."),
 "swan": ("The swan is white.", "Łabędź jest biały."),
 "seagull": ("Seagulls are noisy.", "Mewy są hałaśliwe."),
 "shark": ("Sharks live in the sea.", "Rekiny żyją w morzu."),
 "whale": ("The whale is the biggest animal.", "Wieloryb to największe zwierzę."),
 "dolphin": ("Dolphins are very clever.", "Delfiny są bardzo mądre."),
 "crab": ("There is a crab on the sand.", "Na piasku jest krab."),
 "butterfly": ("The butterfly is beautiful.", "Motyl jest piękny."),
 "mosquito": ("A mosquito bit me.", "Ugryzł mnie komar."),
 "wasp": ("There is a wasp in the room.", "W pokoju jest osa."),
 "worm": ("Birds eat worms.", "Ptaki jedzą robaki."),
 "snail": ("The snail is very slow.", "Ślimak jest bardzo wolny."),
 "squirrel": ("A squirrel is in the tree.", "Wiewiórka jest na drzewie."),
 "hedgehog": ("The hedgehog sleeps in winter.", "Jeż śpi zimą."),
 "bat": ("Bats fly at night.", "Nietoperze latają nocą."),
 "camel": ("Camels live in the desert.", "Wielbłądy żyją na pustyni."),
 "zebra": ("A zebra is black and white.", "Zebra jest czarno-biała."),
 "crocodile": ("The crocodile is in the water.", "Krokodyl jest w wodzie."),
 "turtle": ("The turtle is very old.", "Żółw jest bardzo stary."),
 "penguin": ("Penguins can't fly.", "Pingwiny nie potrafią latać."),
 "tail": ("The dog's tail is long.", "Ogon psa jest długi."),
 "wing": ("The bird has a broken wing.", "Ptak ma złamane skrzydło."),
 "paw": ("The cat's paw is white.", "Łapa kota jest biała."),
 "fur": ("The rabbit has soft fur.", "Królik ma miękkie futro."),
 "feather": ("There is a feather on the ground.", "Na ziemi leży pióro."),
 "pet": ("Do you have a pet?", "Masz zwierzę domowe?"),
 "cage": ("The bird is in the cage.", "Ptak jest w klatce."),
 # ---- zwroty
 "Excuse me": ("Excuse me, where is the station?", "Przepraszam, gdzie jest dworzec?"),
 "I'm sorry": ("I'm sorry, it is my fault.", "Przepraszam, to moja wina."),
 "Thank you": ("Thank you for your help.", "Dziękuję za pomoc."),
 "You're welcome": ("Thanks! — You're welcome.", "Dzięki! — Nie ma za co."),
 "Please": ("Two coffees, please.", "Dwie kawy, proszę."),
 "Here you are": ("Here you are, that's your change.", "Proszę, to twoja reszta."),
 "Nice to meet you": ("Nice to meet you, I'm Tom.", "Miło mi, jestem Tom."),
 "See you later": ("See you later!", "Do zobaczenia później!"),
 "Take care": ("Take care, drive safely.", "Trzymaj się, jedź ostrożnie."),
 "Have a nice day": ("Have a nice day!", "Miłego dnia!"),
 "Good luck": ("Good luck with your test!", "Powodzenia na teście!"),
 "Never mind": ("Never mind, it's not important.", "Nieważne, to nie jest ważne."),
 "No problem": ("Can you help me? — No problem.", "Możesz mi pomóc? — Nie ma sprawy."),
 "Of course": ("Of course I can help you.", "Oczywiście, że mogę ci pomóc."),
 "Sure": ("Sure, take my pen.", "Jasne, weź mój długopis."),
 "I agree": ("I agree with you.", "Zgadzam się z tobą."),
 "I don't agree": ("Sorry, I don't agree.", "Przykro mi, nie zgadzam się."),
 "I think so": ("Is he at home? — I think so.", "Czy on jest w domu? — Chyba tak."),
 "I don't know": ("I don't know his name.", "Nie znam jego imienia."),
 "I'm not sure": ("I'm not sure about this.", "Nie jestem tego pewien."),
 "Could you repeat that?": ("Sorry, could you repeat that?", "Przepraszam, możesz powtórzyć?"),
 "Could you speak slower?": ("Could you speak slower, please?", "Możesz mówić wolniej, proszę?"),
 "What does it mean?": ("What does this word mean?", "Co znaczy to słowo?"),
 "How do you say... in English?": ("How do you say 'magazyn' in English?", "Jak powiedzieć „magazyn” po angielsku?"),
 "I don't understand": ("Sorry, I don't understand.", "Przepraszam, nie rozumiem."),
 "Can you help me?": ("Can you help me, please?", "Możesz mi pomóc, proszę?"),
 "Just a moment": ("Just a moment, please.", "Chwileczkę, proszę."),
 "Let me check": ("Let me check the schedule.", "Niech sprawdzę harmonogram."),
 "It depends": ("It depends on the weather.", "To zależy od pogody."),
 "That's right": ("That's right, well done.", "Zgadza się, dobra robota."),
 "I'm afraid not": ("Is the shop open? — I'm afraid not.", "Czy sklep jest otwarty? — Niestety nie."),
 "Never mind that": ("Never mind that, let's start.", "Nieważne, zaczynajmy."),
 "What's up?": ("Hi Tom, what's up?", "Cześć Tom, co słychać?"),
 "How are you?": ("Hello! How are you?", "Cześć! Jak się masz?"),
 "I'm fine, thanks": ("How are you? — I'm fine, thanks.", "Jak się masz? — W porządku, dzięki."),
 "Long time no see": ("Hi! Long time no see!", "Cześć! Kopę lat!"),
 "Well done": ("Well done, that was perfect.", "Dobra robota, to było świetne."),
 "Watch out!": ("Watch out! The floor is wet.", "Uważaj! Podłoga jest mokra."),
 "Hurry up!": ("Hurry up, the bus is here!", "Pospiesz się, autobus już jest!"),
 "Cheers": ("Cheers, thanks a lot!", "Dzięki, wielkie dzięki!"),
})


if __name__ == "__main__":
    import json, os, glob
    base = os.path.join(os.path.dirname(__file__), "..", "data", "slownictwo")
    n = 0
    for f in glob.glob(os.path.join(base, "*.json")):
        d = json.load(open(f, encoding="utf-8"))
        ch = False
        for it in d.get("items", []):
            if it.get("en") in EX and "pl" in it:
                it["example"], it["example_pl"] = EX[it["en"]]
                ch = True; n += 1
        if ch:
            json.dump(d, open(f, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print("przykłady dopisane:", n)

